const sample_candidates = [
    {
        id:"1",
        name: "Jeya Chandran",
        email: "jeyachandranjcs@gmail.com",
        phone: "1234567890",
        jobTitle: "FullStack Developer",
        image:"https://drive.google.com/file/d/1pDdnMuD5rvS41upP7KK8c8quK_wsGDv2/view?usp=sharing",
        status: "Reviewed",
        resumeUrl: "https://drive.google.com/file/d/1g1iVvO4QKLIqIDMhLFIKatztvqj6iQpK/view",
        referredAt: new Date("2025-1-10"),
      },{
      id:"2",
      name: "John Doe",
      email: "john.doe@example.com",
      phone: "1234567890",
      jobTitle: "Software Developer",
      image:"https://photoai.com/cdn-cgi/image/format=jpeg,fit=cover,width=1024,height=1536,quality=85/https://r2-us-west.photoai.com/1725042039-b6f50f195364bbc1ecb3d4ab2aa8b68e-1.png",
      status: "Pending",
      resumeUrl: "https://example.com/resume/john_doe.pdf",
      referredAt: new Date("2023-12-01"),
    },
    {
      id:"3",
      name: "Jane Smith",
      email: "jane.smith@example.com",
      phone: "9876543210",
      jobTitle: "Data Analyst",
      image:"https://imgv3.fotor.com/images/ai-headshot-generator/AI-generated-LinkedIn-profile-picture--of-a-smiling-male-in-the-light-brown-business-suit-with-his-back-to-the-window-from-Fotor.jpg",
      status: "Reviewed",
      resumeUrl: "https://example.com/resume/jane_smith.pdf",
      referredAt: new Date("2023-12-05"),
    },
    {
      id:"4",
      name: "Michael Brown",
      email: "michael.brown@example.com",
      phone: "5647382910",
      jobTitle: "Frontend Developer",
      image:"https://imgv3.fotor.com/images/ai-headshot-generator/AI-generated-headshot-of-a-man-wearing-black-and-white-business-suit-and-tie-with-his-back-to-the-window-by-Fotor-AI-LinkedIn-photo-generator.jpg",
      status: "Hired",
      resumeUrl: "https://example.com/resume/michael_brown.pdf",
      referredAt: new Date("2023-12-10"),
    },
    {
      id:"5",
      name: "Emily Davis",
      email: "emily.davis@example.com",
      phone: "1122334455",
      jobTitle: "Product Manager",
      image:"https://imgv3.fotor.com/images/ai-headshot-generator/AI-generated-headshot-of-a-female-in-dark-grey-attire-standing-her-back-to-a-builing-view-window-by-Fotor-AI-LinkedIn-photo-generator.jpg",
      status: "Pending",
      resumeUrl: "https://example.com/resume/emily_davis.pdf",
      referredAt: new Date("2023-12-15"),
    },
    {
      id:"6",
      name: "Chris Wilson",
      email: "chris.wilson@example.com",
      phone: "9988776655",
      jobTitle: "Backend Engineer",
      image:"https://imgv3.fotor.com/images/ai-headshot-generator/headshot-of-a-smiling-man-wearing-the-dark-blue-business-shirt-generated-by-Fotor-AI-LinkedIn-photo-generator.jpg",
      status: "Pending",
      resumeUrl: "https://example.com/resume/chris_wilson.pdf",
      referredAt: new Date("2023-12-20"),
    },
    {
      id:"7",
      name: "Olivia Johnson",
      email: "olivia.johnson@example.com",
      phone: "4455667788",
      jobTitle: "UI/UX Designer",
      image:"https://imgv3.fotor.com/images/ai-headshot-generator/headshot-of-a-female-with-long-hair-in-the-blue-business-attire-generated-by-Fotor-AI-LinkedIn-photo-generator.jpg",
      status: "Reviewed",
      resumeUrl: "https://example.com/resume/olivia_johnson.pdf",
      referredAt: new Date("2023-12-25"),
    },
    {
      id:"8",
      name: "Liam Martin",
      email: "liam.martin@example.com",
      phone: "6677889900",
      jobTitle: "DevOps Engineer",
      image:"https://imgv3.fotor.com/images/ai-headshot-generator/AI-generated-indoor-headshot-of-a-man-wearing-a-dark-grey-and-white-business-attire-by-Fotor-AI-headshot-generator.jpg",
      status: "Hired",
      resumeUrl: "https://example.com/resume/liam_martin.pdf",
      referredAt: new Date("2023-12-30"),
    },
    {
      id:"9",
      name: "Sophia White",
      email: "sophia.white@example.com",
      phone: "5544332211",
      jobTitle: "Cybersecurity Analyst",
      image:"https://imgv3.fotor.com/images/ai-headshot-generator/AI-generated-professional-headshot-of-a-feamle-wearing-a-grey-business-attire-by-Fotorr.jpg",
      status: "Pending",
      resumeUrl: "https://example.com/resume/sophia_white.pdf",
      referredAt: new Date("2024-01-03"),
    },
    {
      id:"10",
      name: "Ethan Walker",
      email: "ethan.walker@example.com",
      phone: "3344556677",
      jobTitle: "Machine Learning Engineer",
      image:"https://imgv3.fotor.com/images/ai-headshot-generator/AI-generated-professional-headshot-of-a-smiling-man-wearing-a-blur-business-attire-by-Fotor.jpg",
      status: "Reviewed",
      resumeUrl: "https://example.com/resume/ethan_walker.pdf",
      referredAt: new Date("2024-01-10"),
    },
  ];
  
 module.exports={sample_candidates};
  